resourceType: ValueSet
id: us-core-problem-or-health-concern
url: http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern
name: USCoreProblemOrHealthConcern
title: US Core Problem or Health Concern
status: draft
experimental: true
date: 2022-09-29
description: Code set for category codes for *US Core Condition Problems and Health
  Concerns Profile* consisting of the concepts "problem" and "health-concern".
copyright: Used by permission of HL7 International, all rights reserved Creative Commons
  License
compose:
  include:
  - system: http://terminology.hl7.org/CodeSystem/condition-category
    concept:
    - code: problem-list-item
  - system: http://hl7.org/fhir/us/core/CodeSystem/condition-category
    concept:
    - code: health-concern
