resourceType: ValueSet
id: simple-observation

url: 'http://hl7.org/fhir/us/core/ValueSet/simple-observation'

name: USCoreSimpleObservationCodes
title: US Core Simple Observation Codes
status: active
experimental: false
description: This value set includes all LOINC codes and the SNOMED CT finding hierarchy codes
copyright: |-

  1. This material contains content from LOINC (http://loinc.org). LOINC is copyright © 1995-2020, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc
  2. This value set includes content from SNOMED CT, which is copyright © 2002+ International Health Terminology  Standards Development Organisation (IHTSDO), and distributed by agreement between IHTSDO and HL7. Implementer use of SNOMED CT is not covered by this agreement.

compose:

  include:
    - system: 'http://loinc.org'
    - 
      system: 'http://snomed.info/sct'
      filter:
        - 
          property: concept
          op: is-a
          value: '404684003' #finding (finding)

